# Generated by Django 6.0.8 on 2026-08-05 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('plan', models.CharField(default='basico', max_length=50)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('planeado', 'Planeado'), ('en_ejecucion', 'En ejecucion'), ('finalizado', 'Finalizado')], default='planeado', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('imagen_principal', models.CharField(blank=True, default='', max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='proyectos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('profesional', 'Profesional'), ('empresarial', 'Empresarial')], default='basico', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('almacenamiento_gb', models.IntegerField(default=5)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='proyectos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='proyectos.empresa')),
            ],
        ),
    ]
