# Generated by Django 5.2.16 on 2026-08-25 15:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_ciudad_proyecto_porcentaje_avance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='porcentaje_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_inspeccion', models.CharField(choices=[('avance_general', 'Avance general'), ('estructura', 'Estructura'), ('fachada_acabados', 'Fachada y acabados'), ('instalaciones', 'Instalaciones'), ('otro', 'Otro')], default='avance_general', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_visita', models.DateField()),
                ('porcentaje_avance_reportado', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_realizadas', to='proyectos.usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='inspecciones/%Y/%m/')),
                ('categoria', models.CharField(blank=True, default='', max_length=50)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='proyectos.inspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('inspeccion_creada', 'Inspección creada'), ('inspeccion_corregida', 'Inspección corregida'), ('inspeccion_confirmada', 'Inspección confirmada'), ('avance_actualizado', 'Avance actualizado')], max_length=30)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_bitacora', to='proyectos.inspeccion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='proyectos.proyecto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_registradas', to='proyectos.usuario')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
