# Generated by Django 6.0.8 on 2026-08-25 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_porcentaje_avance_inspeccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dos_fa_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('colaborador', 'Colaborador'), ('gerente', 'Gerente')], default='colaborador', max_length=20),
        ),
        migrations.CreateModel(
            name='SesionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('dispositivo', models.CharField(blank=True, default='', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='proyectos.usuario')),
            ],
        ),
    ]
